### ISSUE TITLE
Feature request: test class/method selection

### ISSUE THREAD

**Issue by m4lysh** [gojuno/composer#105]
Hi,

I really like this project, I find it much more stable than spoon. However there is one feature in spoon that I use extensively that is not supported by composer - a possibility to select a test class and method to execute. In spoon it is done by passing the following arguments:
```
--class-name        Test class name to run (fully-qualified)
--method-name       Test method name to run (must also use --class-name)
```

Could it be implemented in the composer? Or is there any other possible approach that would allow to run a subset of tests?

**Comment by artem-zinnatullin** [comment]
Hi @m4lysh!

It's already supported, unlike Spoon we don't want to enforce JUnit related parameters to Composer API. 

But it's supported through `--instrumentation-arguments` and then [`AndroidJUnitRunner`](https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner.html) or your custom runner will take care of that, we should probably add an example to readme :)

ie

```console
--instrumentation-arguments class com.example.Test
```

Here is documentation about [arguments supported by AndroidJUnitRunner](https://developer.android.com/studio/test/command-line.html#AMOptionsSyntax).

**Comment by artem-zinnatullin** [comment]
Also, I'd wait for #104 to merge, it improves handling of multiple arguments so you can specify let's say two or many separate test cases, but simple use cases of running one class or one test method already supported :)

**Comment by artem-zinnatullin** [comment]
I'm closing this, if you have questions or additions — feel free to comment, if something doesn't work — we'll reopen it, but I use this feature personally so it should be fine :)
