### ISSUE TITLE
Assumption violation treated as a failure

### ISSUE THREAD

**Issue by koral--** [gojuno/composer#112]
Composer treats assumption failure as a test failure:
https://github.com/gojuno/composer/blob/beae497b3c8d03a6dd7b1fea0136f5adfe492592/composer/src/main/kotlin/com/gojuno/composer/Instrumentation.kt#L158
Is that intentional? Shouldn't assumption failures cause 'Ignored' result?

Example: an app showing camera preview with a toggle button changing camera facing. On devices with single cameras (like Nexus 7 2012) button is not displayed. So tests using that button can have assumption that there is more than one camera.

Spoon (via Gradle plugin v 1.2.2) treats assumption failures as success. That's not perfect but tests can be launched on a farm containing devices with single cameras and result is successful if there are no failures.

**Comment by yunikkk** [comment]
Hey,
that wasn't intentional, i guess. We should mark them as ignored, totally agree.

**Comment by artem-zinnatullin** [comment]
Yep, totally my bad!

+1 to mark them as `Ignored`

**Comment by koral--** [comment]
There is a PR with marking them as `Ignored`. However, I'm not sure what to do with violation stacktrace. Should it be added to reports just like stacktraces from `Failed` tests?

**Comment by artem-zinnatullin** [comment]
If you mean JUnit4 xml report then I'm pretty sure that most of parsers like Jenkins JUnit plugin don't expect stacktrace in Ignored tests https://github.com/jenkinsci/junit-plugin/blob/b98cb6eba3b1207a3eba70a2e0766f3e26953b4e/src/main/java/hudson/tasks/junit/CaseResult.java#L226

**Comment by koral--** [comment]
OK, so it seems that the only thing to do is to add that stacktrace to HTML report.

**Comment by artem-zinnatullin** [comment]
As far as I remember we don't handle stacktrace in HTML reports (yet?), logcat will be collected as and displayed as usual, but would be nice to add it here:

https://github.com/gojuno/composer/blob/25ddfa0237d013262ad9410dbc6c8abbd0a68f8e/composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullTest.kt#L83

So eventually HTML report could consume it without changes in Composer core.
