### ISSUE TITLE
Support for screenshot?

### ISSUE THREAD

**Issue by ripunjayasaran** [gojuno/composer#114]
Is there any way to take screenshot and embed it in the Composer report? I did not see anything specific pertaining to this in the readme file (apart from the fact that it was mentioned that screenshot support is there for Composer). 
Spoon has a method to take screenshots and they show up in the report. I was wondering if something similar has been implemented for Composer or not? This is not a bug, but more of an inquiry.

**Comment by plastiv** [comment]
Composer is compatible with Spoon screenshot file structure. Just use spoon dependency to create screenshot and it will show up at the report.

**Comment by artem-zinnatullin** [comment]
Or write custom screenshoter that'll follow Spoon directory structure :)

**Comment by loveshjain** [comment]
We were using spoon before this and taking screenshots was working absolutely fine with that but when I added composer plugin and running the tests, it is creating a folder with package name but not adding any screenshots. I believe it is not taking screenshot at the first place using Composer. Could you please let me know is there anything I am missing here.

I even added Snapshot version of Spoon but no luck.

**Comment by ripunjayasaran** [comment]
@loveshjain : screenshot feature is broken in the new (2.0) version of Spoon. See https://github.com/square/spoon/issues/484#issuecomment-385475744 for a solution for this.

**Comment by loveshjain** [comment]
HI @ripunjayasaran @artem-zinnatullin Thanks for the reply. I did tried square/spoon#484 (comment) but with no luck. I also tried taking the screenshot using spoon only and it worked so I don't think it is an spoon issue. Could you please let me know how you guys are taking the screenshot and folder structure using spoon and composer

**Comment by artem-zinnatullin** [comment]
Sure, Composer just pull screenshots from Spoon-compatible folder structure, here is the code https://github.com/gojuno/composer/blob/v0.3.3/composer/src/main/kotlin/com/gojuno/composer/TestRun.kt#L157
