### ISSUE TITLE
Add device model to HTML reports

### ISSUE THREAD

**Issue by koral--** [gojuno/composer#122]
Currently reports look like that:
![image](https://user-images.githubusercontent.com/3340954/35648823-50b0af14-06d7-11e8-9181-b0f1163dc32c.png)
While in spoon it is:
![image](https://user-images.githubusercontent.com/3340954/35648865-712cb1de-06d7-11e8-944d-e783b0744b4f.png)

At least labels in badges should contain user-friendly device names.

**Comment by artem-zinnatullin** [comment]
Ah yeah, since we were using set of same emulators with Composer we just didn't even think about need in that user-friendly device names

PR is certainly welcomed, I believe we get current names from `adb devices` so getting user-friendly name could require some additional querying through `adb`

**Comment by evgengal** [comment]
Can you add device model to XML reports please? Espresso knows how to do this, but the names contain a lot of extra. (examle: TEST-Nexus_5(AVD) - 6.0-1cc3ab8db2838ac3-QA.xml )

**Comment by artem-zinnatullin** [comment]
Let's do it in separate PRs pls :)

**Comment by evgengal** [comment]
Unfortunately, I can not do this. I don't know kotlin.

**Comment by koral--** [comment]
@artem-zinnatullin @yunikkk could you release commander with the latest commit included? It is required for PR in composer.

**Comment by artem-zinnatullin** [comment]
Sure, @yunikkk you want to do it or I should? (I don't feel super comfortable triggering CI I don't own anymore..)

**Comment by yunikkk** [comment]
@artem-zinnatullin yep, sorry for long response

**Comment by evgengal** [comment]
When to wait for the next release?

**Comment by koral--** [comment]
It is already released: https://github.com/gojuno/composer/releases/tag/v0.3.1

**Comment by evgengal** [comment]
All names are "Android SDK Built For X86"
What am I doing wrong?

![screenshot from 2018-02-22 07-47-46](https://user-images.githubusercontent.com/26863746/36520933-06b05a0c-17a5-11e8-956a-ac233e20027f.png)

**Comment by koral--** [comment]
"Android SDK Built For X86" is a value of `ro.product.model` property on emulators and it's the source of label for HTML reports.

Are you sure that `Emulator(id=emulator-5554, name=Nexus_5) is ready.` is produced by composer?

**Comment by evgengal** [comment]
Yes, I am sure. By the way "-prop name=value " also do not work:
![compozz](https://user-images.githubusercontent.com/26863746/36639115-dcd4961c-1a15-11e8-9fae-bb2a128d3b56.png)

**Comment by koral--** [comment]
It's a log from swarmer: https://github.com/gojuno/swarmer/blob/192ff3053ae2f76b61d16af3d79e7469e44e4166/swarmer/src/main/kotlin/com/gojuno/swarmer/Emulators.kt#L67

You are setting `ro.product.name` but in composer only `ro.product.model` matters. Try setting model.

**Comment by evgengal** [comment]
-prop ro.product.model - does not work.
but options: 
-prop persist.sys.language=ru -prop persist.sys.country=RU - applied.
![compozz2](https://user-images.githubusercontent.com/26863746/36641751-36e5e6da-1a46-11e8-8bce-66557757cf34.png)

**Comment by koral--** [comment]
I've just just checked and proprty setting does not work for me in emulator 27.1.10:
```
$ emulator @test -prop persist.sys.language=ru -prop persist.sys.country=RU -prop ro.product.model=test&

$ adb -e shell getprop |grep RU
$ adb -e shell getprop |grep psersist
```

Looks like a bug in emulator.
