### ISSUE TITLE
Continue test run in case of crash

### ISSUE THREAD

**Issue by evgengal** [gojuno/composer#131]
I have a test run on 5 emulators and more than 50 tests. 
Is it possible to continue the run for the rest of the emulators if an RuntimeException appeared on one emulator?

Full error:
![screenshot from 2018-03-28 06-40-27](https://user-images.githubusercontent.com/26863746/38007646-14a03218-3253-11e8-8ace-b1943f4f3683.png)

**Comment by artem-zinnatullin** [comment]
It's not easy on Composer level atm. 

To implement it we need to know what tests are going to be run #66, which we don't do atm and collect this information as test execution goes.

Or we need an Orchestrator/etc #90 that'll handle application crash and hide it from Composer.

**Comment by dsvoronin** [comment]
Will be possible here: #135

**Comment by artem-zinnatullin** [comment]
Yep, sounds like "Orchestrator"-specific configuration option.
