### ISSUE TITLE
Error when no test found

### ISSUE THREAD

**Issue by MapleInSpring** [gojuno/composer#132]
Is there a flag like failIfNoTests=false in MVN instead of outputting an Error?

Our use case is that we are keeping a group of tests from annotation and the number of tests may vary. Then the number becomes zero. Composer will output an Error. Is there a way to ignore the Error siliently when there are no tests?

**Comment by dsvoronin** [comment]
Our case: we develop impact analysis tool for ui tests right now, and its absolutely valid case to have all tests skipped if no changes in dependent code was made

**Comment by dsvoronin** [comment]
can we close it?

**Comment by yunikkk** [comment]
Sure, thanks
