### ISSUE TITLE
"Orchestrator like" execution mode

### ISSUE THREAD

**Issue by tagantroy** [gojuno/composer#135]
I would like to execute all tests one by one in different processes as [Orchestrator](https://developer.android.com/training/testing/junit-runner.html#using-android-test-orchestrator) does it.
We can extract all tests names with [dex-test-parser](https://github.com/linkedin/dex-test-parser) and execute tests one by one, in this case we will have valid instrumentation output(@artem-zinnatullin mentioned problems with instrumentation output of orchestrator).
Pros: clean heap for each test
Cons: broken @Parameterized tests

**Comment by artem-zinnatullin** [comment]
I'm chatting with @yunikkk about it, but so far I'm 100% down for it!

I'd like to make it a default mode of running tests, but also configurable:

- Option to clear app data between test executions
- Option to disable this mode completely (might be helpful for those who use dynamic test frameworks or parametrized/etc)

**Comment by artem-zinnatullin** [comment]
@tagantroy let's start small?

PR with parsing tests from `--test-apk` would be great to begin with :)

**Comment by artem-zinnatullin** [comment]
cc @dsvoronin

**Comment by dsvoronin** [comment]
Add me as reviewer please, @tagantroy . And i'll be happy to add next things on top of it.
