### ISSUE TITLE
How to display screenshots in HTML report

### ISSUE THREAD

**Issue by tir38** [gojuno/composer#165]
I ran Composer and got a full HTML test reports. I can see the screenshots in the generated file structure but I don't see how to view them from inside the HTML report. When I click on individual tests in the HTML report I only see the logs.

**Comment by f-lolom** [comment]
Hello

I have submitted a PR #161 with the fix, but it has not been reviewed yet.
In the meantime, I have uploaded my fork with the fix under the following artifact :  `com.flolom.composer:composer:0.5.1`

**Comment by tir38** [comment]
Great! this look like it's already contained in your PR and #163 So I'll close this issue.

**Comment by adrey** [comment]
@tir38 if you are using gradle plugin you can use custom version of composer 
`dependencies {
 composer "com.flolom.composer:composer:0.5.1"
}`
