### ISSUE TITLE
Ability to return 0 exit code in case of test failures

### ISSUE THREAD

**Issue by vdoshkinn** [gojuno/composer#179]
Hi! 
Could you please add some key to return 0 exit code when some tests were failed?
I'm going to execute my test suite using composer and now composer step breaks my CI pipeline in the middle because 1 exit code returns in case of failed test.

Thank you in advance

**Comment by trevjonez** [comment]
if you wrap your invocation of composer in a bash script you should be able to achieve this without change to the library. additionally it is likely that changes to the process contract like this would result in breaking a ton of other workflows.

**Comment by artem-zinnatullin** [comment]
Please handle it in your ci pipeline, something like this will work if you
can wrap it in bash:

bash -c "set +e; java -jar composer...."

**Comment by vdoshkinn** [comment]
Thanks guys for the quick response.
"java -jar composer.. || exit 0" works for me.
