### ISSUE TITLE
Badge with duration of the test is hard to read.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/composer#52]
It's small and does not have a title, maybe we can just print it as text instead of badge?
<img width="1879" alt="screen shot 2017-06-08 at 3 29 05 pm" src="https://user-images.githubusercontent.com/967132/26928566-4553e466-4c5f-11e7-8118-97825bc170f9.png">

**Comment by navstyachka** [comment]
Closed by #65.
