### ISSUE TITLE
Color of "Passed" text on "Suite" page does not match color on "Suites List" page.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/composer#53]
<img width="1905" alt="screen shot 2017-06-08 at 3 30 53 pm" src="https://user-images.githubusercontent.com/967132/26928644-939bfea6-4c5f-11e7-8c81-994219bdf8fa.png">

Should be green as well:

<img width="1893" alt="screen shot 2017-06-08 at 3 30 46 pm" src="https://user-images.githubusercontent.com/967132/26928660-9d66c74a-4c5f-11e7-88de-f3111c82e548.png">

**Comment by navstyachka** [comment]
Was done in previous pull
