### ISSUE TITLE
Print duration with zeroes. 

### ISSUE THREAD

**Issue by navstyachka** [gojuno/composer#61]
i.e. `00:15:30` instead of `00:15:3`

**Comment by navstyachka** [comment]
I just realized that `:3` is a count of milliseconds, so this seems to be not relevant. I would change that to 'Add hours count' title.

**Comment by artem-zinnatullin** [comment]
Well, we used to see milliseconds in logs so I would keep them :)

**Comment by artem-zinnatullin** [comment]
Fixed in #61.
