### ISSUE TITLE
Hide screenshot block from HTML if no screenshots are available.

### ISSUE THREAD

**Issue by yunikkk** [gojuno/composer#67]
It would be nice to hide the emtpy block without screenshots

![dpc0gbwutrwulqna-ujuoq](https://user-images.githubusercontent.com/2265924/27141280-6f4c7ee2-5130-11e7-8742-0b7a7e452eac.png)

**Comment by navstyachka** [comment]
@artem-zinnatullin @yunikkk Was fixed along with #70 pull.
