### ISSUE TITLE
Long test name breaks HTML layout.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/composer#68]
<img width="1420" alt="screen shot 2017-06-14 at 7 10 15 pm" src="https://user-images.githubusercontent.com/967132/27157555-cdfb14aa-516a-11e7-9b89-2a84b3e355b5.png">

**Comment by navstyachka** [comment]
@artem-zinnatullin duplicates #56

**Comment by vanniktech** [comment]
The test has a typo at the end should be `RideDetails` 💃

**Comment by artem-zinnatullin** [comment]
haha, thanks @vanniktech :)

**Comment by artem-zinnatullin** [comment]
Closing in favor of #56 then.
